// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRMuM9n1HsfAcRRXygMjiUlIFYrSFSOec',
    appId: '1:141324093576:web:acdc4217391e9a4e88773d',
    messagingSenderId: '141324093576',
    projectId: 'foumbotlink',
    authDomain: 'foumbotlink.firebaseapp.com',
    storageBucket: 'foumbotlink.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEELwBpYSnp6Dg2qkhc_56HGJrmG4i_fA',
    appId: '1:141324093576:android:a08e57eb6efd5b7d88773d',
    messagingSenderId: '141324093576',
    projectId: 'foumbotlink',
    storageBucket: 'foumbotlink.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUfI97EhAClbZmCcnJ0xzfBp3MSa9R-Q',
    appId: '1:141324093576:ios:54f2ee6b8ee065ae88773d',
    messagingSenderId: '141324093576',
    projectId: 'foumbotlink',
    storageBucket: 'foumbotlink.firebasestorage.app',
    iosBundleId: 'com.foumbotlik.foumbotlik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgUfI97EhAClbZmCcnJ0xzfBp3MSa9R-Q',
    appId: '1:141324093576:ios:54f2ee6b8ee065ae88773d',
    messagingSenderId: '141324093576',
    projectId: 'foumbotlink',
    storageBucket: 'foumbotlink.firebasestorage.app',
    iosBundleId: 'com.foumbotlik.foumbotlik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRMuM9n1HsfAcRRXygMjiUlIFYrSFSOec',
    appId: '1:141324093576:web:9c4041f10caacb5988773d',
    messagingSenderId: '141324093576',
    projectId: 'foumbotlink',
    authDomain: 'foumbotlink.firebaseapp.com',
    storageBucket: 'foumbotlink.firebasestorage.app',
  );
}
